version: '3.9'

services:
  backend:
    build: ./backend
    ports:
      - "8001:8001"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_HOST=db
    depends_on:
      - db

  db:
    image: postgres:15
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/seed-test-data.sql:/db/seed-test-data.sql
      - ./db/init.sql:/db/init.sql
      - ./db/init.sh:/docker-entrypoint-initdb.d/zzz-init.sh
    environment:
      - SEED_TEST_DATA=${SEED_TEST_DATA:-false}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"

volumes:
  postgres_data: