import { Module } from '@nestjs/common';
import { TypeOrmModule } from '@nestjs/typeorm';
import { AppController } from './app.controller';
import { AuthModule } from './auth/auth.module';
import {
  ProductsModule,
  UsersModule,
  WarehousesModule,
  OrderModule,
  CategoryModule,
  DiscountModule,
  InventoryMovementModule,
  OrderItemModule,
  ParkingSpotModule,
  ReviewModule,
  SupplyOrderItemModule,
  SupplyOrderModule,
  BatchModule,
  BoxModule,
  LogModule,
  PriceHistoryModule,
  StorageZoneModule,
  SupplierModule,
  TaskModule,
  BatchLocationModule,
} from './bd.models';
import {
  User,
  Category,
  Product,
  Warehouse,
  Discount,
  InventoryMovement,
  OrderItem,
  Order,
  ParkingSpot,
  Review,
  SupplyOrder,
  SupplyOrderItem,
  Supplier,
  Batch,
  Box,
  Log,
  Task,
  PriceHistory,
  StorageZone,
  BatchLocation,
} from './bd.models/entity';
import { MenuModule } from './menu/menu.module';

@Module({
  imports: [
    TypeOrmModule.forRoot({
      type: 'postgres',
      host: process.env.POSTGRES_HOST || 'localhost',
      port: 5432,
      username: process.env.POSTGRES_USER || 'postgres',
      password: process.env.POSTGRES_PASSWORD || 'postgres',
      database: process.env.POSTGRES_DB || 'warehouse_db',
      entities: [
        User,
        Product,
        Category,
        Warehouse,
        Discount,
        InventoryMovement,
        OrderItem,
        Order,
        ParkingSpot,
        Review,
        SupplyOrder,
        SupplyOrderItem,
        Supplier,
        Batch,
        Box,
        Log,
        PriceHistory,
        StorageZone,
        Task,
        BatchLocation,
      ],
      synchronize: false, // true тільки в dev-режимі
      autoLoadEntities: true,
    }),
    UsersModule,
    ProductsModule,
    WarehousesModule,
    AuthModule,
    OrderModule,
    CategoryModule,
    DiscountModule,
    InventoryMovementModule,
    OrderItemModule,
    ParkingSpotModule,
    ReviewModule,
    SupplyOrderItemModule,
    SupplyOrderModule,
    BatchModule,
    BoxModule,
    LogModule,
    PriceHistoryModule,
    StorageZoneModule,
    SupplierModule,
    TaskModule,
    MenuModule, // Добавляем MenuModule
    BatchLocationModule,
  ],
  controllers: [AppController],
  providers: [],
})
export class AppModule {}
